### ISSUE TITLE
password is visible on the UI

### ISSUE THREAD

**Issue by cdupont** [Waziup/wazigate-ui#1]
My password was clearly visible on the UI. Is it voluntary?
![Screenshot from 2019-07-01 16-52-36](https://user-images.githubusercontent.com/484033/60446102-ec5e4b80-9c20-11e9-8b37-b0183d8897a8.png)

**Comment by mojtaba-esk** [comment]
It is when you store it for the first time, if you refresh the page or come again it will not be shown this way.

**Comment by cdupont** [comment]
OK, let's close this for now.
